### ISSUE TITLE
Is the libcaer_cm_encoder missing?

### ISSUE THREAD

**Issue by lennartalff** [ros-event-camera/event_camera_codecs#17]
Hi!

Probably I'm overlooking something here, but shouldn't be there a corresponding `libcaer_cmp_encoder.h` to the `libcaer_cmp_decoder.h` (and for the non compressed variant as well) ?

For `evt3` and `mono` this seems to be the case.

**Comment by berndpfrommer** [comment]
Well, I never really needed a libcaer encoder so I didn't lift out the [implementation within the libcaer driver](https://github.com/ros-event-camera/libcaer_driver/blob/8791c38ffe42a5c8e060329c3994ff0582e95b2d/src/message_converter.cpp#L84).
Do you have a use case where you want to encode in libcaer_cmp format?

**Comment by lennartalff** [comment]
Ah, thank you! That was exactly what I was overlooking. I only skimmed the [README](https://github.com/ros-event-camera/.github/blob/main/profile/README.md) where only the metavision driver was mentioned and didn't go through the available repositories myself.

I greatly appreciate the effort you put into this!
